[profile.release]
panic = 'unwind'

[workspace]
members = ['node', 'runtime/arctic', 'runtime/frost',  "pallets/simple-inflation", "pallets/xcm-helper", "pallets/traits", "pallets/asset-registry", "pallets/currency-adapter", "primitives", "integration-tests"]

